name: Test rtad on all platforms

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  linux:
    name: Linux-${{ matrix.arch }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64, arm64]
        compiler: [gcc, clang]
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake -B build \
          -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C Release

  macos:
    name: macOS-${{ matrix.arch }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64, arm64]
        compiler: [gcc-15, clang]
        include:
          - arch: x64
            os: macos-15-intel
          - arch: arm64
            os: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake -B build \
          -DCMAKE_C_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C Release

  windows:
    name: Windows-${{ matrix.arch }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64, arm64]
        compiler: [msvc, gcc, clang]
        include:
          - arch: x64
            os: windows-latest
          - arch: arm64
            os: windows-11-arm
          - compiler: gcc
            generator: Ninja
          - compiler: clang
            generator: Ninja
          - compiler: msvc
            generator: "Visual Studio 17 2022"
    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.compiler }}
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C Release
    